### ISSUE TITLE
An error is reported when the object name has a special symbol

### ISSUE THREAD

**Issue by chenpaner** [ksami/QRemeshify#2]
When "*" in name,report that:
```
Python: Traceback (most recent call last):
  File "C:\Users\CP\AppData\Roaming\Blender Foundation\Blender\Blender default addon\qremeshify\operator.py", line 67, in execute
    exporter.export_mesh(bm, mesh_filepath)
  File "C:\Users\CP\AppData\Roaming\Blender Foundation\Blender\Blender default addon\qremeshify\util\exporter.py", line 53, in export_mesh
    with open(mesh_filepath, 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'C:\\Users\\CP\\AppData\\Local\\Temp\\blender_a13864\\123*_1.obj'
```

**Comment by ksami** [comment]
Thanks for the report
